// Code generated by ginctl. DO NOT EDIT.

package handler

import (
	"github.com/gin-gonic/gin"
	"net/http"

	"hello/internal/svc"
)

func RegisterHandlers(r *gin.Engine, serverCtx *svc.ServiceContext) {
	g0 := r.Group("/app")
	g0.Handle(http.MethodGet, "/config", ConfigHandler(serverCtx))
	g0.Handle(http.MethodGet, "/health", HealthHandler(serverCtx))
}
