// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type ConfigResp struct {
	Version       int            `json:"version"`
	SystemPrompts []PromptEntity `json:"systemPrompts"`
}

type HealthResp struct {
	Status string `json:"status"`
}

type PromptEntity struct {
	Id      int    `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}
